//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 10:16:36 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cisco.dvbu.com/ps/deploytool/modules")
package com.cisco.dvbu.ps.deploytool.modules;
